// Import PrismaClient from the generated client location (relative path for internal use)
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "./generated/client/client";

// Re-export all types and enums generated by Prisma.
// This allows consumers to import types like 'User', 'Post', 'Prisma.UserCreateInput'
// directly from '@oxford-heavy/data-sources-prisma'.
export * from "./generated/client/client";

// Export the PrismaClient class for type usage
export { PrismaClient };

// Export the adapter type for consumers
export { PrismaPg };

/**
 * Resolves the database URL from environment variables.
 * Priority: DATABASE_URL > Default local URL.
 *
 * DATABASE_URL is used in production (set via Infisical/platform secrets), or to set an external DB for
 * development purposes (e.g., Supabase).
 * The default local URL is used as a fallback for dev environments.
 */
export function getDatabaseUrl(): string {
  const url =
    process.env.DATABASE_URL ||
    "postgresql://postgres:postgres@127.0.0.1:5432/postgres?schema=public";
  return url;
}

/**
 * Creates a PostgreSQL adapter for Prisma 7+.
 * If no URL is provided, resolves from environment variables.
 *
 * @param connectionString - Optional PostgreSQL connection URL. If not provided,
 *                          resolves from environment variable.
 * @returns A configured PrismaPg adapter instance
 */
export function createPrismaAdapter(connectionString?: string): PrismaPg {
  const url = connectionString ?? getDatabaseUrl();
  return new PrismaPg({ connectionString: url });
}
